network:
  name: nflow
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'

  # normalizing flow network (RealNVP)
  nflow:
    latent_size: 1920  # The size of the latent space
    hidden_size: 1024  # The number of the hidden units
    n_flows: 4  # Number of flows
    hidden_layers: 1  # The number of hidden layers in st_network
    clamp_value: 3.0  # The value used for clamping st_network outputs
    clamp_method: "ATAN"  # The clamp method, choices: [HARD, TANH, SIGMOID, ATAN]
    clamp_t: False  # Whether to clamp the t-network outputs as well as s-network outputs
    l2_normalize: True  # l2-normalize the input of the nflow network
    arch: "RealNVP" # The architecture of the normalizing flow, choices: [RealNVP, Glow, NSF, ResFlow]

  # network used for feature extraction and aggregation
  backbone:
    name: feat_concat
    num_gpus: '@{num_gpus}'
    processing: null

    # feature aggregation network
    feat_agg:
      layers: [1, 3, 6, 9, 12]

    # network used for feature extraction
    encoder:
      name: vit3d
      num_classes: '@{dataset.num_classes}'
      num_channels: '@{dataset.num_channels}'
      image_size: '@{dataset.image_size}'
      hidden_size: 384
      mlp_dim: 1536
      num_heads: 12
      num_layers: 12
      pretrained: False
      checkpoint: none
      num_gpus: '@{num_gpus}'
