network:
  name: feat_concat
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
  processing: ['avg_pool_2d']

  # feature aggregation network
  feat_agg:
    layers: [1, 2, 3, 4, 5]

  # network used for feature extraction
  encoder:
    name: resnet18_224x224
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    checkpoint: none
    checkpoint_key: none
    num_gpus: '@{num_gpus}'
