network:
  name: vae
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'

  # variational auto-encoder network
  vae:
    input_dim: 512  # The size of the vae input (base model latent size)
    hidden_dims: [512, 256, 128, 64]  # The number of the hidden units
    latent_dim: 64  # The size of the vae latent space
    l2_normalize: True  # l2-normalize the input of the vae

  # network used for feature extraction
  backbone:
    name: resnet3d_18
    num_classes: '@{dataset.num_classes}'
    num_channels: '@{dataset.num_channels}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    checkpoint: none
    checkpoint_key: none
    num_gpus: '@{num_gpus}'
