network:
  name: feat_concat
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
  processing: null

  # feature aggregation network
  feat_agg:
    layers: [1, 3, 6, 9, 12]

  # network used for feature extraction
  encoder:
    name: vit3d
    num_classes: '@{dataset.num_classes}'
    num_channels: '@{dataset.num_channels}'
    image_size: '@{dataset.image_size}'
    hidden_size: 384
    mlp_dim: 1536
    num_heads: 12
    num_layers: 12
    pretrained: False  # set 'True' to load pretrained model
    checkpoint: none   # ignore if pretrained is false
    num_gpus: '@{num_gpus}'
