exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_'@{mark}'/s'@{seed}'"
output_dir: ./results/
save_output: True
merge_option: default
mark: default
seed: 0
nondeterministic_operators: 'Error'

dataset:
  # cached features extracted from classifier
  feat_root: './results/cifar10_resnet18_32x32_feat_extract_nflow_default/s0'
  z_normalize_feat: False

num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0

pipeline:
  name: train_nflow

trainer:
  name: nflow

evaluator:
  name: ood

optimizer:
  name: adam
  num_epochs: 100
  lr: 0.0001
  betas: [0.5, 0.999]
  grad_clip_norm: 1.0
  weight_decay: 0.0001

recorder:
  name: nflow
  save_all_models: False
  save_last_model: False
